//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("SegCoModel", "fk_clave_articulo", "articulos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SegCoWebServices.articulos), "etiquetas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SegCoWebServices.etiquetas), true)]
[assembly: EdmRelationshipAttribute("SegCoModel", "fk_etiquetas", "etiquetas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SegCoWebServices.etiquetas), "paquetes_det", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SegCoWebServices.paquetes_det), true)]
[assembly: EdmRelationshipAttribute("SegCoModel", "fk_paquetes", "paquetes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SegCoWebServices.paquetes), "paquetes_det", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SegCoWebServices.paquetes_det), true)]

#endregion

namespace SegCoWebServices
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SegCoEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SegCoEntities usando la cadena de conexión encontrada en la sección 'SegCoEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SegCoEntities() : base("name=SegCoEntities", "SegCoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SegCoEntities.
        /// </summary>
        public SegCoEntities(string connectionString) : base(connectionString, "SegCoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SegCoEntities.
        /// </summary>
        public SegCoEntities(EntityConnection connection) : base(connection, "SegCoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<articulos> articulos
        {
            get
            {
                if ((_articulos == null))
                {
                    _articulos = base.CreateObjectSet<articulos>("articulos");
                }
                return _articulos;
            }
        }
        private ObjectSet<articulos> _articulos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<etiquetas> etiquetas
        {
            get
            {
                if ((_etiquetas == null))
                {
                    _etiquetas = base.CreateObjectSet<etiquetas>("etiquetas");
                }
                return _etiquetas;
            }
        }
        private ObjectSet<etiquetas> _etiquetas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<paquetes> paquetes
        {
            get
            {
                if ((_paquetes == null))
                {
                    _paquetes = base.CreateObjectSet<paquetes>("paquetes");
                }
                return _paquetes;
            }
        }
        private ObjectSet<paquetes> _paquetes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<paquetes_det> paquetes_det
        {
            get
            {
                if ((_paquetes_det == null))
                {
                    _paquetes_det = base.CreateObjectSet<paquetes_det>("paquetes_det");
                }
                return _paquetes_det;
            }
        }
        private ObjectSet<paquetes_det> _paquetes_det;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet articulos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToarticulos(articulos articulos)
        {
            base.AddObject("articulos", articulos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet etiquetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToetiquetas(etiquetas etiquetas)
        {
            base.AddObject("etiquetas", etiquetas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet paquetes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopaquetes(paquetes paquetes)
        {
            base.AddObject("paquetes", paquetes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet paquetes_det. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopaquetes_det(paquetes_det paquetes_det)
        {
            base.AddObject("paquetes_det", paquetes_det);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SegCoModel", Name="articulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articulos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto articulos.
        /// </summary>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        /// <param name="articulo">Valor inicial de la propiedad articulo.</param>
        /// <param name="dias_caducidad">Valor inicial de la propiedad dias_caducidad.</param>
        /// <param name="id_bodega">Valor inicial de la propiedad id_bodega.</param>
        /// <param name="peso_variado">Valor inicial de la propiedad peso_variado.</param>
        /// <param name="parcial">Valor inicial de la propiedad parcial.</param>
        /// <param name="leyenda">Valor inicial de la propiedad leyenda.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        public static articulos Createarticulos(global::System.String clave, global::System.String articulo, global::System.Int32 dias_caducidad, global::System.Int32 id_bodega, global::System.Boolean peso_variado, global::System.Boolean parcial, global::System.Boolean leyenda, global::System.String unidad)
        {
            articulos articulos = new articulos();
            articulos.clave = clave;
            articulos.articulo = articulo;
            articulos.dias_caducidad = dias_caducidad;
            articulos.id_bodega = id_bodega;
            articulos.peso_variado = peso_variado;
            articulos.parcial = parcial;
            articulos.leyenda = leyenda;
            articulos.unidad = unidad;
            return articulos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                if (_clave != value)
                {
                    OnclaveChanging(value);
                    ReportPropertyChanging("clave");
                    _clave = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("clave");
                    OnclaveChanged();
                }
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String articulo
        {
            get
            {
                return _articulo;
            }
            set
            {
                OnarticuloChanging(value);
                ReportPropertyChanging("articulo");
                _articulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("articulo");
                OnarticuloChanged();
            }
        }
        private global::System.String _articulo;
        partial void OnarticuloChanging(global::System.String value);
        partial void OnarticuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dias_caducidad
        {
            get
            {
                return _dias_caducidad;
            }
            set
            {
                Ondias_caducidadChanging(value);
                ReportPropertyChanging("dias_caducidad");
                _dias_caducidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dias_caducidad");
                Ondias_caducidadChanged();
            }
        }
        private global::System.Int32 _dias_caducidad;
        partial void Ondias_caducidadChanging(global::System.Int32 value);
        partial void Ondias_caducidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                Onid_bodegaChanging(value);
                ReportPropertyChanging("id_bodega");
                _id_bodega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_bodega");
                Onid_bodegaChanged();
            }
        }
        private global::System.Int32 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int32 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean peso_variado
        {
            get
            {
                return _peso_variado;
            }
            set
            {
                Onpeso_variadoChanging(value);
                ReportPropertyChanging("peso_variado");
                _peso_variado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peso_variado");
                Onpeso_variadoChanged();
            }
        }
        private global::System.Boolean _peso_variado;
        partial void Onpeso_variadoChanging(global::System.Boolean value);
        partial void Onpeso_variadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean parcial
        {
            get
            {
                return _parcial;
            }
            set
            {
                OnparcialChanging(value);
                ReportPropertyChanging("parcial");
                _parcial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parcial");
                OnparcialChanged();
            }
        }
        private global::System.Boolean _parcial;
        partial void OnparcialChanging(global::System.Boolean value);
        partial void OnparcialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean leyenda
        {
            get
            {
                return _leyenda;
            }
            set
            {
                OnleyendaChanging(value);
                ReportPropertyChanging("leyenda");
                _leyenda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("leyenda");
                OnleyendaChanged();
            }
        }
        private global::System.Boolean _leyenda;
        partial void OnleyendaChanging(global::System.Boolean value);
        partial void OnleyendaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cantidad_fija
        {
            get
            {
                return _cantidad_fija;
            }
            set
            {
                Oncantidad_fijaChanging(value);
                ReportPropertyChanging("cantidad_fija");
                _cantidad_fija = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad_fija");
                Oncantidad_fijaChanged();
            }
        }
        private Nullable<global::System.Int32> _cantidad_fija;
        partial void Oncantidad_fijaChanging(Nullable<global::System.Int32> value);
        partial void Oncantidad_fijaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> piezas
        {
            get
            {
                return _piezas;
            }
            set
            {
                OnpiezasChanging(value);
                ReportPropertyChanging("piezas");
                _piezas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("piezas");
                OnpiezasChanged();
            }
        }
        private Nullable<global::System.Int32> _piezas;
        partial void OnpiezasChanging(Nullable<global::System.Int32> value);
        partial void OnpiezasChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SegCoModel", "fk_clave_articulo", "etiquetas")]
        public EntityCollection<etiquetas> etiquetas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<etiquetas>("SegCoModel.fk_clave_articulo", "etiquetas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<etiquetas>("SegCoModel.fk_clave_articulo", "etiquetas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SegCoModel", Name="etiquetas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class etiquetas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto etiquetas.
        /// </summary>
        /// <param name="id_etiqueta">Valor inicial de la propiedad id_etiqueta.</param>
        /// <param name="tipo_etiqueta">Valor inicial de la propiedad tipo_etiqueta.</param>
        /// <param name="clave_articulo">Valor inicial de la propiedad clave_articulo.</param>
        /// <param name="fecha_empaque">Valor inicial de la propiedad fecha_empaque.</param>
        /// <param name="fecha_caducidad">Valor inicial de la propiedad fecha_caducidad.</param>
        /// <param name="id_bodega">Valor inicial de la propiedad id_bodega.</param>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static etiquetas Createetiquetas(global::System.Int64 id_etiqueta, global::System.String tipo_etiqueta, global::System.String clave_articulo, global::System.DateTime fecha_empaque, global::System.DateTime fecha_caducidad, global::System.Int64 id_bodega, global::System.Int64 id_usuario, global::System.Decimal cantidad, global::System.String unidad, global::System.String estatus)
        {
            etiquetas etiquetas = new etiquetas();
            etiquetas.id_etiqueta = id_etiqueta;
            etiquetas.tipo_etiqueta = tipo_etiqueta;
            etiquetas.clave_articulo = clave_articulo;
            etiquetas.fecha_empaque = fecha_empaque;
            etiquetas.fecha_caducidad = fecha_caducidad;
            etiquetas.id_bodega = id_bodega;
            etiquetas.id_usuario = id_usuario;
            etiquetas.cantidad = cantidad;
            etiquetas.unidad = unidad;
            etiquetas.estatus = estatus;
            return etiquetas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_etiqueta
        {
            get
            {
                return _id_etiqueta;
            }
            set
            {
                if (_id_etiqueta != value)
                {
                    Onid_etiquetaChanging(value);
                    ReportPropertyChanging("id_etiqueta");
                    _id_etiqueta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_etiqueta");
                    Onid_etiquetaChanged();
                }
            }
        }
        private global::System.Int64 _id_etiqueta;
        partial void Onid_etiquetaChanging(global::System.Int64 value);
        partial void Onid_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo_etiqueta
        {
            get
            {
                return _tipo_etiqueta;
            }
            set
            {
                Ontipo_etiquetaChanging(value);
                ReportPropertyChanging("tipo_etiqueta");
                _tipo_etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo_etiqueta");
                Ontipo_etiquetaChanged();
            }
        }
        private global::System.String _tipo_etiqueta;
        partial void Ontipo_etiquetaChanging(global::System.String value);
        partial void Ontipo_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_proveedor
        {
            get
            {
                return _id_proveedor;
            }
            set
            {
                Onid_proveedorChanging(value);
                ReportPropertyChanging("id_proveedor");
                _id_proveedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proveedor");
                Onid_proveedorChanged();
            }
        }
        private Nullable<global::System.Int32> _id_proveedor;
        partial void Onid_proveedorChanging(Nullable<global::System.Int32> value);
        partial void Onid_proveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_lote
        {
            get
            {
                return _id_lote;
            }
            set
            {
                Onid_loteChanging(value);
                ReportPropertyChanging("id_lote");
                _id_lote = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_lote");
                Onid_loteChanged();
            }
        }
        private Nullable<global::System.Int64> _id_lote;
        partial void Onid_loteChanging(Nullable<global::System.Int64> value);
        partial void Onid_loteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_pedido
        {
            get
            {
                return _id_pedido;
            }
            set
            {
                Onid_pedidoChanging(value);
                ReportPropertyChanging("id_pedido");
                _id_pedido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_pedido");
                Onid_pedidoChanged();
            }
        }
        private Nullable<global::System.Int64> _id_pedido;
        partial void Onid_pedidoChanging(Nullable<global::System.Int64> value);
        partial void Onid_pedidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave_articulo
        {
            get
            {
                return _clave_articulo;
            }
            set
            {
                Onclave_articuloChanging(value);
                ReportPropertyChanging("clave_articulo");
                _clave_articulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave_articulo");
                Onclave_articuloChanged();
            }
        }
        private global::System.String _clave_articulo;
        partial void Onclave_articuloChanging(global::System.String value);
        partial void Onclave_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_empaque
        {
            get
            {
                return _fecha_empaque;
            }
            set
            {
                Onfecha_empaqueChanging(value);
                ReportPropertyChanging("fecha_empaque");
                _fecha_empaque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_empaque");
                Onfecha_empaqueChanged();
            }
        }
        private global::System.DateTime _fecha_empaque;
        partial void Onfecha_empaqueChanging(global::System.DateTime value);
        partial void Onfecha_empaqueChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_caducidad
        {
            get
            {
                return _fecha_caducidad;
            }
            set
            {
                Onfecha_caducidadChanging(value);
                ReportPropertyChanging("fecha_caducidad");
                _fecha_caducidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_caducidad");
                Onfecha_caducidadChanged();
            }
        }
        private global::System.DateTime _fecha_caducidad;
        partial void Onfecha_caducidadChanging(global::System.DateTime value);
        partial void Onfecha_caducidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                Onid_bodegaChanging(value);
                ReportPropertyChanging("id_bodega");
                _id_bodega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_bodega");
                Onid_bodegaChanged();
            }
        }
        private global::System.Int64 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int64 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int64 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int64 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> piezas
        {
            get
            {
                return _piezas;
            }
            set
            {
                OnpiezasChanging(value);
                ReportPropertyChanging("piezas");
                _piezas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("piezas");
                OnpiezasChanged();
            }
        }
        private Nullable<global::System.Int64> _piezas;
        partial void OnpiezasChanging(Nullable<global::System.Int64> value);
        partial void OnpiezasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipo_salida
        {
            get
            {
                return _tipo_salida;
            }
            set
            {
                Ontipo_salidaChanging(value);
                ReportPropertyChanging("tipo_salida");
                _tipo_salida = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipo_salida");
                Ontipo_salidaChanged();
            }
        }
        private global::System.String _tipo_salida;
        partial void Ontipo_salidaChanging(global::System.String value);
        partial void Ontipo_salidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_recepcion
        {
            get
            {
                return _fecha_recepcion;
            }
            set
            {
                Onfecha_recepcionChanging(value);
                ReportPropertyChanging("fecha_recepcion");
                _fecha_recepcion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_recepcion");
                Onfecha_recepcionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_recepcion;
        partial void Onfecha_recepcionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_recepcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_entrega
        {
            get
            {
                return _fecha_entrega;
            }
            set
            {
                Onfecha_entregaChanging(value);
                ReportPropertyChanging("fecha_entrega");
                _fecha_entrega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_entrega");
                Onfecha_entregaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_entrega;
        partial void Onfecha_entregaChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_entregaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SegCoModel", "fk_clave_articulo", "articulos")]
        public articulos articulos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("SegCoModel.fk_clave_articulo", "articulos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("SegCoModel.fk_clave_articulo", "articulos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<articulos> articulosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articulos>("SegCoModel.fk_clave_articulo", "articulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<articulos>("SegCoModel.fk_clave_articulo", "articulos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SegCoModel", "fk_etiquetas", "paquetes_det")]
        public EntityCollection<paquetes_det> paquetes_det
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<paquetes_det>("SegCoModel.fk_etiquetas", "paquetes_det");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<paquetes_det>("SegCoModel.fk_etiquetas", "paquetes_det", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SegCoModel", Name="paquetes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paquetes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto paquetes.
        /// </summary>
        /// <param name="id_paquete">Valor inicial de la propiedad id_paquete.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        /// <param name="id_pedido">Valor inicial de la propiedad id_pedido.</param>
        /// <param name="fecha_creacion">Valor inicial de la propiedad fecha_creacion.</param>
        /// <param name="fecha_caducidad">Valor inicial de la propiedad fecha_caducidad.</param>
        public static paquetes Createpaquetes(global::System.Int32 id_paquete, global::System.String estatus, global::System.Decimal cantidad, global::System.String unidad, global::System.Int32 id_pedido, global::System.DateTime fecha_creacion, global::System.DateTime fecha_caducidad)
        {
            paquetes paquetes = new paquetes();
            paquetes.id_paquete = id_paquete;
            paquetes.estatus = estatus;
            paquetes.cantidad = cantidad;
            paquetes.unidad = unidad;
            paquetes.id_pedido = id_pedido;
            paquetes.fecha_creacion = fecha_creacion;
            paquetes.fecha_caducidad = fecha_caducidad;
            return paquetes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_paquete
        {
            get
            {
                return _id_paquete;
            }
            set
            {
                if (_id_paquete != value)
                {
                    Onid_paqueteChanging(value);
                    ReportPropertyChanging("id_paquete");
                    _id_paquete = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_paquete");
                    Onid_paqueteChanged();
                }
            }
        }
        private global::System.Int32 _id_paquete;
        partial void Onid_paqueteChanging(global::System.Int32 value);
        partial void Onid_paqueteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_pedido
        {
            get
            {
                return _id_pedido;
            }
            set
            {
                Onid_pedidoChanging(value);
                ReportPropertyChanging("id_pedido");
                _id_pedido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_pedido");
                Onid_pedidoChanged();
            }
        }
        private global::System.Int32 _id_pedido;
        partial void Onid_pedidoChanging(global::System.Int32 value);
        partial void Onid_pedidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_creacion
        {
            get
            {
                return _fecha_creacion;
            }
            set
            {
                Onfecha_creacionChanging(value);
                ReportPropertyChanging("fecha_creacion");
                _fecha_creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_creacion");
                Onfecha_creacionChanged();
            }
        }
        private global::System.DateTime _fecha_creacion;
        partial void Onfecha_creacionChanging(global::System.DateTime value);
        partial void Onfecha_creacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_caducidad
        {
            get
            {
                return _fecha_caducidad;
            }
            set
            {
                Onfecha_caducidadChanging(value);
                ReportPropertyChanging("fecha_caducidad");
                _fecha_caducidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_caducidad");
                Onfecha_caducidadChanged();
            }
        }
        private global::System.DateTime _fecha_caducidad;
        partial void Onfecha_caducidadChanging(global::System.DateTime value);
        partial void Onfecha_caducidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clave_articulo
        {
            get
            {
                return _clave_articulo;
            }
            set
            {
                Onclave_articuloChanging(value);
                ReportPropertyChanging("clave_articulo");
                _clave_articulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("clave_articulo");
                Onclave_articuloChanged();
            }
        }
        private global::System.String _clave_articulo;
        partial void Onclave_articuloChanging(global::System.String value);
        partial void Onclave_articuloChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SegCoModel", "fk_paquetes", "paquetes_det")]
        public EntityCollection<paquetes_det> paquetes_det
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<paquetes_det>("SegCoModel.fk_paquetes", "paquetes_det");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<paquetes_det>("SegCoModel.fk_paquetes", "paquetes_det", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SegCoModel", Name="paquetes_det")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paquetes_det : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto paquetes_det.
        /// </summary>
        /// <param name="id_detalle">Valor inicial de la propiedad id_detalle.</param>
        /// <param name="id_paquete">Valor inicial de la propiedad id_paquete.</param>
        /// <param name="id_etiqueta">Valor inicial de la propiedad id_etiqueta.</param>
        public static paquetes_det Createpaquetes_det(global::System.Int32 id_detalle, global::System.Int32 id_paquete, global::System.Int64 id_etiqueta)
        {
            paquetes_det paquetes_det = new paquetes_det();
            paquetes_det.id_detalle = id_detalle;
            paquetes_det.id_paquete = id_paquete;
            paquetes_det.id_etiqueta = id_etiqueta;
            return paquetes_det;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_detalle
        {
            get
            {
                return _id_detalle;
            }
            set
            {
                if (_id_detalle != value)
                {
                    Onid_detalleChanging(value);
                    ReportPropertyChanging("id_detalle");
                    _id_detalle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_detalle");
                    Onid_detalleChanged();
                }
            }
        }
        private global::System.Int32 _id_detalle;
        partial void Onid_detalleChanging(global::System.Int32 value);
        partial void Onid_detalleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_paquete
        {
            get
            {
                return _id_paquete;
            }
            set
            {
                Onid_paqueteChanging(value);
                ReportPropertyChanging("id_paquete");
                _id_paquete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_paquete");
                Onid_paqueteChanged();
            }
        }
        private global::System.Int32 _id_paquete;
        partial void Onid_paqueteChanging(global::System.Int32 value);
        partial void Onid_paqueteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_etiqueta
        {
            get
            {
                return _id_etiqueta;
            }
            set
            {
                Onid_etiquetaChanging(value);
                ReportPropertyChanging("id_etiqueta");
                _id_etiqueta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_etiqueta");
                Onid_etiquetaChanged();
            }
        }
        private global::System.Int64 _id_etiqueta;
        partial void Onid_etiquetaChanging(global::System.Int64 value);
        partial void Onid_etiquetaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SegCoModel", "fk_etiquetas", "etiquetas")]
        public etiquetas etiquetas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<etiquetas>("SegCoModel.fk_etiquetas", "etiquetas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<etiquetas>("SegCoModel.fk_etiquetas", "etiquetas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<etiquetas> etiquetasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<etiquetas>("SegCoModel.fk_etiquetas", "etiquetas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<etiquetas>("SegCoModel.fk_etiquetas", "etiquetas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SegCoModel", "fk_paquetes", "paquetes")]
        public paquetes paquetes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paquetes>("SegCoModel.fk_paquetes", "paquetes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paquetes>("SegCoModel.fk_paquetes", "paquetes").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<paquetes> paquetesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paquetes>("SegCoModel.fk_paquetes", "paquetes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<paquetes>("SegCoModel.fk_paquetes", "paquetes", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
